spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        namespace: 38963eda-85d2-48cc-9b08-fe3a2aa6b62f
#        cluster-name: SH

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"


user:
  name: sean77

rocketmq:
  name-server: 127.0.0.1:9876