spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

server:
  port: 9092

feign:
  client:
    config:
#      nacos-provider:
#        loggerLevel: full
      # 全局配置
      default:
        loggerLevel: full
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    com.sean.feign.service.EchoService: debug


rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    # 必须指定group
    group: test-group